### ISSUE TITLE
Support Confluence fixed tables  

### ISSUE THREAD

**Issue by raphj** [xwikisas/xwiki-pro-macros#361]
For proper rendering of migrated content, we need this in the Confluence style sheet:

```css
table.fixed-table {
  table-layout: fixed;
}
```
